name: CI/CD Pipeline for Spring Boot Clinic App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Spring Boot App
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: clinic
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Configure database for tests
      - name: Set up database connection
        run: |
          echo "spring.datasource.url=jdbc:mysql://localhost:3306/clinic?useSSL=false&serverTimezone=UTC" > src/main/resources/application-test.properties
          echo "spring.datasource.username=root" >> src/main/resources/application-test.properties
          echo "spring.datasource.password=root" >> src/main/resources/application-test.properties

      # Step 5: Build and Test the application
      - name: Build and Test
        run: |
          mvn clean test
          mvn package -DskipTests=false

          
