name: Build & Deploy Clinic App

on:
  push:
    branches:
      - master

jobs:
  maven-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        # options: >
        #   --health-cmd="mysqladmin ping" --health-interval=10s
        #   --health-timeout=5s --health-retries=3
    

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Run Unit Tests
        run: cd Clinic && mvn -B test

      - name: Build with Maven
        run: cd Clinic && mvn -B package

      - name: Archive JAR file
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: Clinic/target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: app
          path: Clinic/target

      - name: Build Docker Image
        run: |
          cd Clinic
          docker build -f DockerFile -t asaad90/clinic-app:latest .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u asaad90 --password-stdin

      - name: Push Docker Image
        run: docker push asaad90/clinic-app:latest
